version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123

  app:
    build: .
    container_name: nestjs-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://root:root123@mongo:27017/nest?authSource=admin
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo-data:
    driver: local